version: '3.5'

# This docker-compose file is for running local development
#
# to update the base image, run 'docker-compose build'
# and then run 'docker-compose up' to create the development environmet
# with the current code bind-mounted into the container for fast development

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/web
    ports:
      - 8080:80
