version: '3.5'

# This docker-compose file is for running in a local production-like context
# it does not mount the volume

services:
  web:
    image: divinumofficiumweb/divinumofficium:latest
    ports:
      - 80:80
