name: build

# Test of CI build of docker image

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    # Build the image regularly (each Friday) to get new security fixes, even if pushes don't occur
    - cron: '13 23 * * 5'

jobs:
  build:
    name: Build, scan & push
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t divinumofficiumweb/divinumofficium:citest .
      
      # TODO : get push working
      #- name: Docker login
      #  run: >-
      #    echo "${{ secrets.GHCR_TOKEN }}"
      #    | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
          
      #- name: Push image to GitHub
      #  run: |
      #    docker push ghcr.io/wonderfall/nextcloud
      #    docker push ghcr.io/wonderfall/nextcloud:$(grep -oP '(?<=NEXTCLOUD_VERSION=).*' Dockerfile | head -c6)
      #    docker push ghcr.io/wonderfall/nextcloud:$(grep -oP '(?<=NEXTCLOUD_VERSION=).*' Dockerfile | head -c2)
